import = [
    "~/.config/alacritty/themes/hyper.toml",
]

[window]
startup_mode = "Maximized"

[font.normal]
family = "MesloLGS NF"

[keyboard]
bindings = [
    {key= "ArrowLeft", mods="Command|Alt", action="SelectPreviousTab"},
    {key= "ArrowRight", mods="Command|Alt", action="SelectNextTab"},
]